[package]
name = "devy"
version = "0.1.0"
authors = ["mtKeller (RE||EK iO) <micah.t.keller@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.3.0"
deno_core ="0.67.0"